drupal_content_sync.flow.*:
  type: config_entity
  label: 'Flow config'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: 'Name'
    sync_entities:
      type: map
      label: 'Sync entities'
    local_connections:
      type: map
      label: 'Local Drupal Content Sync Connections'

drupal_content_sync.pool.*:
  type: config_entity
  label: 'Drupal Content Sync Pool'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    backend_url:
      type: uri
      label: 'Drupal Content Sync URL'
    site_id:
      type: string
      label: 'Site Identifier'

action.configuration.node_drupal_content_sync_export_action:
  type: action_configuration_default
  label: 'Push changes'